services:
  - docker

script:
  - docker build .

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    skip_join: true
    channels:
      - "irc.freenode.org#gnocchi"
